"""Org creation: admin-first, in one transaction. The only supported way to make an org.

"Create the org, then add an admin" has a window with zero admins, and a crash inside it leaves
an org only an engineer with database access can rescue. The audit head is seeded here too, and
``org.created`` is the chain's first event (seq 1), in the same transaction. So is the org's row
in ``ssc.org_index``, the unscoped list workers use to find every org (decision 009 amendment):
an org that exists is always discoverable, and a rolled-back org never is. The org's opaque
``cell_label``, the middle of its app hosts, is generated by the column's default (revision 0011).
"""

from dataclasses import dataclass
from typing import Final

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from ssc_contracts.audit import ActorKind, AuditAction
from ssc_contracts.ids import new_id
from ssc_control.audit.chain import GENESIS_HASH, Actor, NewEvent, append_event
from ssc_control.db.bind import bound_org

__all__ = ["GENESIS_HASH", "SYSTEM_ACTOR", "CreatedOrg", "NewOrg", "all_org_ids", "create_org"]

SYSTEM_ACTOR: Final = Actor(kind=ActorKind.OPERATOR, id="system:create_org")


@dataclass(frozen=True, slots=True)
class NewOrg:
    name: str
    admin_display_name: str
    admin_email: str
    admin_issuer: str
    admin_subject: str


@dataclass(frozen=True, slots=True)
class CreatedOrg:
    org_id: str
    admin_user_id: str
    identity_link_id: str
    cell_label: str


_INSERT_ORG = text("insert into ssc.org (id, name) values (:id, :name) returning cell_label")
_INSERT_ADMIN = text(
    "insert into ssc.user_account (id, org_id, display_name, email, role) "
    "values (:id, :org, :name, :email, 'admin')"
)
_INSERT_LINK = text(
    "insert into ssc.identity_link (id, org_id, user_id, issuer, subject) "
    "values (:id, :org, :user, :issuer, :subject)"
)
_INSERT_HEAD = text("insert into ssc.audit_head (org_id, seq, hash) values (:org, 0, :hash)")
_INSERT_INDEX = text("insert into ssc.org_index (org_id) values (:org)")
_ALL_ORG_IDS = text("select org_id from ssc.org_index order by org_id")


async def create_org(
    engine: AsyncEngine, spec: NewOrg, *, actor: Actor | None = None
) -> CreatedOrg:
    """Create the org, its first admin and audit chain; ``actor`` defaults to the system."""
    org_id, admin_id, link_id = new_id("org"), new_id("usr"), new_id("idl")
    async with bound_org(engine, org_id) as conn:
        label = (await conn.execute(_INSERT_ORG, {"id": org_id, "name": spec.name})).scalar_one()
        await conn.execute(
            _INSERT_ADMIN,
            {
                "id": admin_id,
                "org": org_id,
                "name": spec.admin_display_name,
                "email": spec.admin_email,
            },
        )
        await conn.execute(
            _INSERT_LINK,
            {
                "id": link_id,
                "org": org_id,
                "user": admin_id,
                "issuer": spec.admin_issuer,
                "subject": spec.admin_subject,
            },
        )
        await conn.execute(_INSERT_HEAD, {"org": org_id, "hash": GENESIS_HASH})
        await conn.execute(_INSERT_INDEX, {"org": org_id})
        await append_event(
            conn,
            NewEvent(
                org_id=org_id,
                action=AuditAction.ORG_CREATED,
                actor=actor or SYSTEM_ACTOR,
                target_kind="org",
                target_id=org_id,
                after={"name": spec.name},
            ),
        )
    return CreatedOrg(
        org_id=org_id, admin_user_id=admin_id, identity_link_id=link_id, cell_label=str(label)
    )


async def all_org_ids(engine: AsyncEngine) -> list[str]:
    """Every org id, from ``ssc.org_index``: the one read that crosses orgs. It needs no bind
    and returns ids only; do the org's work inside ``bound_org(engine, org_id)``."""
    async with engine.connect() as conn:
        ids = (await conn.execute(_ALL_ORG_IDS)).scalars().all()
        await conn.rollback()
    return list(ids)
