"""Write RESULTS.md from the records store."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from loginproof import join
from loginproof.config import SSO_PROVIDERS

RESULTS = Path(__file__).resolve().parent.parent / "RESULTS.md"


def yn(v: Any) -> str:
    if v is True:
        return "yes"
    if v is False:
        return "no"
    return str(v) if v else join.NOT_MEASURED


SKIPPED: frozenset[str] = frozenset({"ENTRA_OIDC", "ENTRA_SAML"})
"""Providers left out of the proof; see README.md."""


def render(records: dict[str, Any]) -> str:
    ev = join.evaluate(records)
    device = records.get("device", {})
    flow = device.get("flow", {})
    recheck = device.get("recheck", {})
    if not flow:
        cli = join.NOT_MEASURED
    elif flow.get("offered") is False:
        cli = "device flow not offered"
    elif recheck:
        cli = yn(recheck.get("token_revoked_on_deactivation"))
    else:
        cli = "flow ran, revocation not re-checked"

    lines = [
        "# SSC-002 results: WorkOS login vendor proof",
        "",
        "Generated by `uv run python -m loginproof report`. Rows say `not measured` until the founder runs the checklist in README.md.",
        "",
        "| Provider | Logins | Directory users | Join key | Stable across email change | CLI token revoked on deactivation | Group sharing possible |",
        "|---|---:|---:|---|---|---|---|",
    ]
    for p in SSO_PROVIDERS:
        r = ev.get(p)
        if not r and p in SKIPPED:
            lines.append(f"| {p} | skipped (founder decision 2026-09-30) | | | | | |")
            continue
        if not r:
            lines.append(
                f"| {p} | 0 | 0 | {join.NOT_MEASURED} | {join.NOT_MEASURED} | {cli} | {join.NOT_MEASURED} |"
            )
            continue
        lines.append(
            f"| {p} | {r['logins']} | {r['directory_users']} | {r['join_key'] or 'none'} | "
            f"{yn(r['stable_across_email_change'])} | {cli} | {yn(r['group_sharing_possible'])} |"
        )
    lines += [
        "",
        (
            "Join key meanings: `idp_id` means the SSO profile's `idp_id` equals the directory user's `idp_id`. "
            "`directory.raw_attributes.<path>` means the SSO `idp_id` was found only inside that directory attribute. "
            "`login.raw_attributes.<claim> == directory.idp_id` means an SSO raw claim carries the directory id. "
            "`email` means only the email matched, which is not a stable key."
        ),
        "",
        "## Device flow",
        "",
        "Measured with a Google Workspace user; timings and what was not measured: NOTES.md section h.",
        "",
        f"- Offered: {yn(flow.get('offered')) if flow else join.NOT_MEASURED}",
        f"- Refresh before deactivation succeeded: {yn(device.get('before_deactivation', {}).get('refresh_succeeded'))}",
        f"- Refresh after deactivation HTTP: {recheck.get('refresh_http', join.NOT_MEASURED)}, error: {recheck.get('refresh_error')}",
        f"- Sessions after deactivation: {recheck.get('sessions', join.NOT_MEASURED)}",
        "",
        "## Fallback design when a provider has no stable key",
        "",
        "Used for any row whose join key is `email` or `none` (the docs already say Google SAML cannot send an `id` claim, see NOTES.md).",
        "",
        "1. On first login, create the SSC user from the SSO profile and store `(connection_id, idp_id, email)` as the login identity.",
        "2. Try to attach a directory user: exact `idp_id`, then the raw-attribute paths listed above, then a unique lower-cased email match. Record which rule fired in the audit log.",
        "3. If nothing matches, the user has no groups. Sharing with a group does not include them until an admin links the records.",
        "4. Admin console: an `Unlinked logins` list with a `Link to directory user` action. The link is stored on the SSC user, never inferred again, and the action is audited.",
        "5. When the directory later sends an email change, the stored link holds. When the SSO email changes and the link was made by email, the next login falls into `Unlinked logins` again and the admin re-links; the old link is kept for the audit trail.",
        "6. Directory `state = inactive` or `dsync.user.deleted` removes the user from every group immediately and revokes their SSC sessions through our own session store, regardless of what WorkOS does with its refresh tokens.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    from loginproof import store

    RESULTS.write_text(render(store.load()))
    print(f"wrote {RESULTS}")
