/**
 * Projects the TypeScript tokens into `tokens.css` as `--ssc-*` custom properties. The CSS is
 * generated and committed; `test/tokens.test.ts` fails when it is stale, and
 * `npm run gen:tokens` rewrites it.
 */

import {
  EFFECTS,
  FONT_FAMILIES,
  GRADIENTS,
  LAYOUT,
  MOTION,
  RADIUS,
  SPACE,
  THEME_TOKENS,
  TYPE,
  type SemanticTokens,
  type Theme,
} from './semantic';

export const PREFIX = 'ssc';

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

export const tokenVar = (name: string) => `--${PREFIX}-${kebab(name)}`;

function themeBlock(theme: Theme, indent: string): string {
  const colours = THEME_TOKENS[theme];
  const lines = [
    `color-scheme: ${theme};`,
    ...(Object.keys(colours) as (keyof SemanticTokens)[]).map((k) => `${tokenVar(k)}: ${colours[k]};`),
    ...Object.entries(EFFECTS[theme]).map(([k, v]) => `${tokenVar(k)}: ${v};`),
  ];
  return lines.map((l) => `${indent}${l}`).join('\n');
}

/** The tokens that are the same in both themes, as `[custom property, value]`. */
export function sharedTokens(): readonly (readonly [string, string])[] {
  const group = (prefix: string, values: Readonly<Record<string, string>>) =>
    Object.entries(values).map(([k, v]) => [`--${PREFIX}-${prefix}${kebab(k)}`, v] as const);
  return [
    ...group('font-', FONT_FAMILIES),
    ...group('type-', TYPE),
    ...group('radius-', RADIUS),
    ...group('space-', SPACE),
    ...group('', LAYOUT),
    ...group('', MOTION),
    ...group('', GRADIENTS),
  ];
}

function sharedBlock(): string {
  return sharedTokens()
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');
}

export function emitCss(): string {
  return [
    '/* Generated by src/tokens/emit.ts from the Delimitus UI tokens (ef688e9b) and the landing',
    "   page's (landing/index.html). Do not edit; run `npm run gen:tokens`. */",
    '',
    ':root {',
    sharedBlock(),
    '}',
    '',
    ":root,\n[data-theme='light'] {",
    themeBlock('light', '  '),
    '}',
    '',
    "[data-theme='dark'] {",
    themeBlock('dark', '  '),
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    "  :root:not([data-theme='light']) {",
    themeBlock('dark', '    '),
    '  }',
    '}',
    '',
  ].join('\n');
}
