/**
 * Projects the TypeScript tokens into `tokens.css` as `--ssc-*` custom properties. The CSS is
 * generated and committed; `test/tokens.test.ts` fails when it is stale, and
 * `npm run gen:tokens` rewrites it.
 */

import { EFFECTS, FONT_FAMILIES, RADIUS, THEME_TOKENS, type SemanticTokens, type Theme } from './semantic';

export const PREFIX = 'ssc';

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

export const tokenVar = (name: string) => `--${PREFIX}-${kebab(name)}`;

function themeBlock(theme: Theme, indent: string): string {
  const colours = THEME_TOKENS[theme];
  const lines = [
    `color-scheme: ${theme};`,
    ...(Object.keys(colours) as (keyof SemanticTokens)[]).map((k) => `${tokenVar(k)}: ${colours[k]};`),
    ...Object.entries(EFFECTS[theme]).map(([k, v]) => `${tokenVar(k)}: ${v};`),
  ];
  return lines.map((l) => `${indent}${l}`).join('\n');
}

function sharedBlock(): string {
  return [
    ...Object.entries(FONT_FAMILIES).map(([k, v]) => `  --${PREFIX}-font-${k}: ${v};`),
    ...Object.entries(RADIUS).map(([k, v]) => `  --${PREFIX}-radius-${k}: ${v};`),
  ].join('\n');
}

export function emitCss(): string {
  return [
    '/* Generated by src/tokens/emit.ts from the Delimitus UI tokens (ef688e9b). Do not edit;',
    '   run `npm run gen:tokens`. */',
    '',
    ':root {',
    sharedBlock(),
    '}',
    '',
    ":root,\n[data-theme='light'] {",
    themeBlock('light', '  '),
    '}',
    '',
    "[data-theme='dark'] {",
    themeBlock('dark', '  '),
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    "  :root:not([data-theme='light']) {",
    themeBlock('dark', '    '),
    '  }',
    '}',
    '',
  ].join('\n');
}
