/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat */
        post: operations["heartbeat_internal_v1_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approvals
         * @description Newest first. Org admins and operators see every request; others see their own. An
         *     operator's read is audited as ``operator.access``.
         */
        get: operations["list_approvals_v1_approvals_get"];
        put?: never;
        /**
         * Create Approval
         * @description Ask another admin of the org to approve one change to one environment. Allowed to the
         *     environment's builders, its app's owner and org admins, agent sessions included.
         */
        post: operations["create_approval_v1_approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Approval
         * @description One request. A request the caller may not see is ``NOT_FOUND``.
         */
        get: operations["get_approval_v1_approvals__approval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approval_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Approval
         * @description Record what an org admin decided. Operator credentials only, never in an agent session.
         *     Refused, in this order: not an operator, an agent session, no such request, already decided,
         *     the approver asked for it, the approver is not an active org admin.
         */
        post: operations["decide_approval_v1_approvals__approval_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Apps */
        get: operations["list_apps_v1_apps_get"];
        put?: never;
        /** Create App */
        post: operations["create_app_v1_apps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App */
        get: operations["get_app_v1_apps__app_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps/{app_id}/environments/{environment_id}/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Deployment
         * @description Start a deployment: 202 plus a ``Location`` to poll. Running it is the reconciler's job.
         */
        post: operations["create_deployment_v1_apps__app_id__environments__environment_id__deployments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps/{app_id}/environments/{environment_id}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Grants */
        get: operations["get_grants_v1_apps__app_id__environments__environment_id__grants_get"];
        /**
         * Put Grants
         * @description Replace the sharing rules of one environment. Requires ``If-Match`` with the current ETag.
         *
         *     A change that needs approval is not applied: an agent session gets ``202`` and the pending
         *     approval ids (asked for here); a person gets ``APPROVAL_REQUIRED`` naming what to ask for.
         */
        put: operations["put_grants_v1_apps__app_id__environments__environment_id__grants_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Audit
         * @description The org's audit events, newest first, in keyset pages. Org admins only.
         */
        get: operations["search_audit_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Audit
         * @description Every matching event as a CSV or JSON-lines download, itself recorded as
         *     ``audit.exported``. Org admins in their own session only; agent credentials are refused.
         */
        get: operations["export_audit_v1_audit_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation */
        get: operations["get_operation_v1_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_v1_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorKind
         * @enum {string}
         */
        ActorKind: "user" | "workload" | "schedule" | "operator" | "integration";
        /** AppCreate */
        AppCreate: {
            /**
             * Slug
             * @description Host label of the app. Lower-case, no leading digit, no `--`.
             */
            slug: string;
        };
        /** AppList */
        AppList: {
            /** Apps */
            apps: components["schemas"]["AppSummary"][];
        };
        /** AppOut */
        AppOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Environments */
            environments: components["schemas"]["EnvironmentOut"][];
            /** Id */
            id: string;
            /** Owner User Id */
            owner_user_id: string;
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled" | "quarantined";
        };
        /** AppSummary */
        AppSummary: {
            /** Id */
            id: string;
            /** Owner User Id */
            owner_user_id: string;
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled" | "quarantined";
        };
        /** Approval */
        Approval: {
            /** App Id */
            app_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decided By User Id */
            decided_by_user_id: string | null;
            /** Decision Channel */
            decision_channel: ("email" | "chat" | "console") | null;
            /** Decision Reason */
            decision_reason: string | null;
            /** Environment Id */
            environment_id: string;
            /** Id */
            id: string;
            kind: components["schemas"]["RequirementKind"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Policy Decision Id */
            policy_decision_id: string | null;
            /**
             * Recorded By Operator
             * @description The SSC operator who recorded the decision, when one did.
             */
            recorded_by_operator: string | null;
            /** Requested By User Id */
            requested_by_user_id: string;
            /** Requested Via Agent */
            requested_via_agent: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "approved" | "denied" | "cancelled";
            /**
             * Subject Key
             * @description What exactly is asked: a connection name, a host, or a `sha256:` digest of the grant set (and, for `agent_share`, the grants version it replaces).
             */
            subject_key: string;
        };
        /** ApprovalCreate */
        ApprovalCreate: {
            /** Environment Id */
            environment_id: string;
            kind: components["schemas"]["RequirementKind"];
            /**
             * Payload
             * @description `widen_audience`: `{grants}`. `agent_share`: `{grants_version, grants}`. Others: `{}`.
             */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Subject Key
             * @description The connection name or host. Derived by the server for `widen_audience` and `agent_share`; when sent for those it must match.
             */
            subject_key?: string | null;
        };
        /** ApprovalPage */
        ApprovalPage: {
            /** Approvals */
            approvals: components["schemas"]["Approval"][];
            /**
             * Next Before
             * @description Pass as `before` for the next, older page; null on the last page.
             */
            next_before: string | null;
        };
        /**
         * AuditAction
         * @enum {string}
         */
        AuditAction: "org.created" | "user.created" | "user.updated" | "user.deactivated" | "user.reactivated" | "group.synced" | "app.created" | "app.owner_transferred" | "app.disabled" | "app.quarantined" | "app.enabled" | "app.deleted" | "login.succeeded" | "login.failed" | "token.issued" | "token.revoked" | "secret.bound" | "secret.rotated" | "secret.removed" | "grant.added" | "grant.removed" | "bundle.stored" | "build.started" | "build.failed" | "release.created" | "deploy.started" | "deploy.finished" | "deploy.failed" | "rollback.started" | "rollback.finished" | "rollback.failed" | "kill_switch.step" | "approval.requested" | "approval.decided" | "schedule.created" | "schedule.updated" | "schedule.paused" | "schedule.resumed" | "schedule.deleted" | "schedule.run_requested" | "connection.created" | "connection.removed" | "operator.access" | "audit.exported" | "audit.reanchored";
        /** AuditActor */
        AuditActor: {
            /** Client Id */
            client_id: string | null;
            /** Id */
            id: string;
            kind: components["schemas"]["ActorKind"];
            /** Via Agent */
            via_agent: boolean;
        };
        /** AuditEvent */
        AuditEvent: {
            action: components["schemas"]["AuditAction"];
            actor: components["schemas"]["AuditActor"];
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /**
             * Hash
             * @description Hex. `sha256(prev_hash || canonical)`.
             */
            hash: string;
            /** Policy Decision Id */
            policy_decision_id: string | null;
            /**
             * Prev Hash
             * @description Hex. The previous event's hash; zeros before seq 1.
             */
            prev_hash: string;
            /** Seq */
            seq: number;
            target: components["schemas"]["AuditTarget"];
        };
        /** AuditPage */
        AuditPage: {
            /** Events */
            events: components["schemas"]["AuditEvent"][];
            /**
             * Next Before Seq
             * @description Pass as `before_seq` for the next, older page; null on the last page.
             */
            next_before_seq: number | null;
        };
        /** AuditTarget */
        AuditTarget: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
        };
        /** DecisionIn */
        DecisionIn: {
            /**
             * Approver User Id
             * @description The org admin who decided, never the requester.
             */
            approver_user_id: string;
            /**
             * Channel
             * @description How the decision reached SSC.
             * @enum {string}
             */
            channel: "email" | "chat";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "approved" | "denied";
            /** Reason */
            reason: string;
        };
        /** DeploymentCreate */
        DeploymentCreate: {
            /**
             * Kind
             * @default deploy
             * @enum {string}
             */
            kind: "deploy" | "rollback";
            /** Release Id */
            release_id: string;
        };
        /** EnvironmentOut */
        EnvironmentOut: {
            /** Config Version */
            config_version: number;
            /** Current Deployment Id */
            current_deployment_id: string | null;
            /** Grants Version */
            grants_version: number;
            /** Id */
            id: string;
            /**
             * Name
             * @enum {string}
             */
            name: "prod" | "preview";
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "VALIDATION_FAILED" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "UNSUPPORTED_MEDIA_TYPE" | "UNAUTHENTICATED" | "FORBIDDEN" | "RATE_LIMITED" | "IDEMPOTENCY_KEY_REQUIRED" | "IDEMPOTENCY_KEY_REUSED" | "IDEMPOTENCY_IN_FLIGHT" | "PRECONDITION_REQUIRED" | "PRECONDITION_STALE" | "ALREADY_EXISTS" | "REFERENCE_NOT_FOUND" | "DEPLOYMENT_IN_FLIGHT" | "LAST_ORG_ADMIN" | "OWNER_NOT_ACTIVE" | "RECORD_IMMUTABLE" | "SCHEDULE_DELETED" | "APPROVAL_REQUIRED" | "APPROVAL_NOT_PENDING" | "SELF_APPROVAL_REFUSED" | "AGENT_SESSION_REFUSED" | "APPROVER_NOT_ELIGIBLE" | "INTERNAL";
        /** GrantIn */
        GrantIn: {
            /**
             * Role
             * @enum {string}
             */
            role: "builder" | "user";
            /**
             * Subject Id
             * @description A `usr_` or `grp_` id; absent when subject_kind is `org`.
             */
            subject_id?: string | null;
            /**
             * Subject Kind
             * @enum {string}
             */
            subject_kind: "user" | "group" | "org";
        };
        /** GrantOut */
        GrantOut: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "builder" | "user";
            /** Subject Id */
            subject_id: string | null;
            /**
             * Subject Kind
             * @enum {string}
             */
            subject_kind: "user" | "group" | "org";
        };
        /** GrantsIn */
        GrantsIn: {
            /** Grants */
            grants: components["schemas"]["GrantIn"][];
        };
        /** GrantsOut */
        GrantsOut: {
            /** Environment Id */
            environment_id: string;
            /** Grants */
            grants: components["schemas"]["GrantOut"][];
            /** Grants Version */
            grants_version: number;
        };
        /**
         * GrantsPending
         * @description An agent session's change, waiting for another admin. Nothing was applied.
         */
        GrantsPending: {
            /**
             * Approval Ids
             * @description Retry the same change once all are approved.
             */
            approval_ids: string[];
            /** Environment Id */
            environment_id: string;
            /**
             * Grants Version
             * @description Unchanged: the version the change will replace.
             */
            grants_version: number;
        };
        /** Heartbeat */
        Heartbeat: {
            /** Cell Label */
            cell_label: string;
            /** Snapshot Version */
            snapshot_version?: number | null;
        };
        /** HeartbeatAck */
        HeartbeatAck: {
            /**
             * Acknowledged
             * @constant
             */
            acknowledged: true;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Org Id */
            org_id: string;
        };
        /** OperationAccepted */
        OperationAccepted: {
            /** Operation Id */
            operation_id: string;
            /**
             * State
             * @constant
             */
            state: "pending";
        };
        /** OperationOut */
        OperationOut: {
            /** App Id */
            app_id: string;
            /** Environment Id */
            environment_id: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "deploy" | "rollback";
            /** Operation Id */
            operation_id: string;
            /** Release Id */
            release_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "healthy" | "failed" | "superseded";
        };
        /**
         * PrincipalKind
         * @enum {string}
         */
        PrincipalKind: "user" | "workload" | "operator";
        /**
         * Problem
         * @description The wire shape of every refusal (RFC 9457). Rendered by exactly one function.
         */
        Problem: {
            code: components["schemas"]["ErrorCode"];
            /**
             * Detail
             * @description Fixed, human-readable explanation. Never carries evidence.
             */
            detail: string;
            /**
             * Instance
             * @description The request path.
             */
            instance: string;
            /**
             * Request Id
             * @description Quote this to support. Evidence is logged under it.
             */
            request_id: string;
            /** Status */
            status: number;
            /**
             * Title
             * @description Fixed, human-readable summary of the code.
             */
            title: string;
            /**
             * Type
             * @description A URL naming the error code.
             */
            type: string;
        };
        /**
         * RequirementKind
         * @description Mirrors the ``ssc.approval_request.kind`` CHECK.
         * @enum {string}
         */
        RequirementKind: "widen_audience" | "connect_data_source" | "enable_internet_hosts" | "agent_share";
        /** Whoami */
        Whoami: {
            /** Client Id */
            client_id: string | null;
            /** Credential Id */
            credential_id: string;
            /** Is Agent */
            is_agent: boolean;
            kind: components["schemas"]["PrincipalKind"];
            /** Org Id */
            org_id: string;
            /** Subject */
            subject: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    heartbeat_internal_v1_heartbeat_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Heartbeat"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatAck"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REQUIRED` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `FORBIDDEN` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_IN_FLIGHT` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REUSED`, `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_approvals_v1_approvals_get: {
        parameters: {
            query?: {
                state?: ("pending" | "approved" | "denied" | "cancelled") | null;
                environment_id?: string | null;
                /** @description The previous page's `next_before`. */
                before?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalPage"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `FORBIDDEN` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_approval_v1_approvals_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalCreate"];
            };
        };
        responses: {
            /** @description The same question is already pending or approved; that request is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REQUIRED` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `FORBIDDEN` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `NOT_FOUND` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_IN_FLIGHT` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `PRECONDITION_STALE` */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REUSED`, `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_approval_v1_approvals__approval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `FORBIDDEN` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `NOT_FOUND` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    decide_approval_v1_approvals__approval_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REQUIRED` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `FORBIDDEN`, `AGENT_SESSION_REFUSED`, `SELF_APPROVAL_REFUSED`, `APPROVER_NOT_ELIGIBLE` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `NOT_FOUND` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_IN_FLIGHT`, `APPROVAL_NOT_PENDING` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REUSED`, `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_apps_v1_apps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppList"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_app_v1_apps_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppOut"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REQUIRED` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `FORBIDDEN` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_IN_FLIGHT`, `ALREADY_EXISTS` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REUSED`, `VALIDATION_FAILED`, `OWNER_NOT_ACTIVE` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_app_v1_apps__app_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppOut"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `NOT_FOUND` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_deployment_v1_apps__app_id__environments__environment_id__deployments_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                app_id: string;
                environment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationAccepted"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REQUIRED` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `NOT_FOUND` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_IN_FLIGHT`, `DEPLOYMENT_IN_FLIGHT` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `IDEMPOTENCY_KEY_REUSED`, `VALIDATION_FAILED`, `REFERENCE_NOT_FOUND` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_grants_v1_apps__app_id__environments__environment_id__grants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                environment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantsOut"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `NOT_FOUND` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    put_grants_v1_apps__app_id__environments__environment_id__grants_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                app_id: string;
                environment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantsOut"];
                };
            };
            /** @description Made through an agent credential, or widening a data-connected app: waiting for approval. Nothing changed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantsPending"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `FORBIDDEN` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `NOT_FOUND` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `APPROVAL_REQUIRED` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `PRECONDITION_STALE` */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED`, `REFERENCE_NOT_FOUND` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `PRECONDITION_REQUIRED` */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    search_audit_v1_audit_get: {
        parameters: {
            query?: {
                /** @description Inclusive. RFC 3339. */
                since?: string | null;
                /** @description Exclusive. RFC 3339. */
                until?: string | null;
                action?: components["schemas"]["AuditAction"] | null;
                actor_kind?: components["schemas"]["ActorKind"] | null;
                actor_id?: string | null;
                target_kind?: string | null;
                target_id?: string | null;
                /** @description Only events older than this: the previous page's cursor. */
                before_seq?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `FORBIDDEN` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    export_audit_v1_audit_export_get: {
        parameters: {
            query: {
                /** @description Inclusive. RFC 3339. */
                since?: string | null;
                /** @description Exclusive. RFC 3339. */
                until?: string | null;
                action?: components["schemas"]["AuditAction"] | null;
                actor_kind?: components["schemas"]["ActorKind"] | null;
                actor_id?: string | null;
                target_kind?: string | null;
                target_id?: string | null;
                format: "csv" | "jsonl";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matching events, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                    "text/csv": string;
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `FORBIDDEN` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_operation_v1_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `NOT_FOUND` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    whoami_v1_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Whoami"];
                };
            };
            /** @description `UNAUTHENTICATED` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `VALIDATION_FAILED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description `RATE_LIMITED` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
