/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedApprovalsRouteImport } from './routes/_authed/approvals'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedAppsAppIdRouteImport } from './routes/_authed/apps.$appId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApprovalsRoute = AuthedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppsAppIdRoute = AuthedAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthedApprovalsRoute
  '/audit': typeof AuthedAuditRoute
  '/apps/$appId': typeof AuthedAppsAppIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/approvals': typeof AuthedApprovalsRoute
  '/audit': typeof AuthedAuditRoute
  '/': typeof AuthedIndexRoute
  '/apps/$appId': typeof AuthedAppsAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/approvals': typeof AuthedApprovalsRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/apps/$appId': typeof AuthedAppsAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/approvals' | '/audit' | '/apps/$appId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/approvals' | '/audit' | '/' | '/apps/$appId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/approvals'
    | '/_authed/audit'
    | '/_authed/'
    | '/_authed/apps/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/approvals': {
      id: '/_authed/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthedApprovalsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/$appId': {
      id: '/_authed/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AuthedAppsAppIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedApprovalsRoute: typeof AuthedApprovalsRoute
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAppsAppIdRoute: typeof AuthedAppsAppIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApprovalsRoute: AuthedApprovalsRoute,
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAppsAppIdRoute: AuthedAppsAppIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
