/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedConnectionsRouteImport } from './routes/_authed/connections'
import { Route as AuthedEgressRouteImport } from './routes/_authed/egress'
import { Route as AuthedEnvironmentRouteImport } from './routes/_authed/environment'
import { Route as AuthedPeopleRouteImport } from './routes/_authed/people'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthedApprovalsIndexRouteImport } from './routes/_authed/approvals.index'
import { Route as AuthedApprovalsApprovalIdRouteImport } from './routes/_authed/approvals.$approvalId'
import { Route as AuthedAppsAppIdRouteImport } from './routes/_authed/apps.$appId'
import { Route as AuthedAppsAppIdKillSwitchRunIdRouteImport } from './routes/_authed/apps.$appId_.kill-switch.$runId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectionsRoute = AuthedConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEgressRoute = AuthedEgressRouteImport.update({
  id: '/egress',
  path: '/egress',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEnvironmentRoute = AuthedEnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleRoute = AuthedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedApprovalsIndexRoute = AuthedApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApprovalsApprovalIdRoute =
  AuthedApprovalsApprovalIdRouteImport.update({
    id: '/approvals/$approvalId',
    path: '/approvals/$approvalId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAppsAppIdRoute = AuthedAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppsAppIdKillSwitchRunIdRoute =
  AuthedAppsAppIdKillSwitchRunIdRouteImport.update({
    id: '/apps/$appId_/kill-switch/$runId',
    path: '/apps/$appId/kill-switch/$runId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthedAuditRoute
  '/connections': typeof AuthedConnectionsRoute
  '/egress': typeof AuthedEgressRoute
  '/environment': typeof AuthedEnvironmentRoute
  '/people': typeof AuthedPeopleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/approvals/$approvalId': typeof AuthedApprovalsApprovalIdRoute
  '/apps/$appId': typeof AuthedAppsAppIdRoute
  '/approvals/': typeof AuthedApprovalsIndexRoute
  '/apps/$appId/kill-switch/$runId': typeof AuthedAppsAppIdKillSwitchRunIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AuthedAuditRoute
  '/connections': typeof AuthedConnectionsRoute
  '/egress': typeof AuthedEgressRoute
  '/environment': typeof AuthedEnvironmentRoute
  '/people': typeof AuthedPeopleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthedIndexRoute
  '/approvals/$approvalId': typeof AuthedApprovalsApprovalIdRoute
  '/apps/$appId': typeof AuthedAppsAppIdRoute
  '/approvals': typeof AuthedApprovalsIndexRoute
  '/apps/$appId/kill-switch/$runId': typeof AuthedAppsAppIdKillSwitchRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/connections': typeof AuthedConnectionsRoute
  '/_authed/egress': typeof AuthedEgressRoute
  '/_authed/environment': typeof AuthedEnvironmentRoute
  '/_authed/people': typeof AuthedPeopleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/approvals/$approvalId': typeof AuthedApprovalsApprovalIdRoute
  '/_authed/apps/$appId': typeof AuthedAppsAppIdRoute
  '/_authed/approvals/': typeof AuthedApprovalsIndexRoute
  '/_authed/apps/$appId_/kill-switch/$runId': typeof AuthedAppsAppIdKillSwitchRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/connections'
    | '/egress'
    | '/environment'
    | '/people'
    | '/auth/callback'
    | '/approvals/$approvalId'
    | '/apps/$appId'
    | '/approvals/'
    | '/apps/$appId/kill-switch/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/connections'
    | '/egress'
    | '/environment'
    | '/people'
    | '/auth/callback'
    | '/'
    | '/approvals/$approvalId'
    | '/apps/$appId'
    | '/approvals'
    | '/apps/$appId/kill-switch/$runId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/audit'
    | '/_authed/connections'
    | '/_authed/egress'
    | '/_authed/environment'
    | '/_authed/people'
    | '/auth/callback'
    | '/_authed/'
    | '/_authed/approvals/$approvalId'
    | '/_authed/apps/$appId'
    | '/_authed/approvals/'
    | '/_authed/apps/$appId_/kill-switch/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connections': {
      id: '/_authed/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthedConnectionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/egress': {
      id: '/_authed/egress'
      path: '/egress'
      fullPath: '/egress'
      preLoaderRoute: typeof AuthedEgressRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/environment': {
      id: '/_authed/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof AuthedEnvironmentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people': {
      id: '/_authed/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthedPeopleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/approvals/': {
      id: '/_authed/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AuthedApprovalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/approvals/$approvalId': {
      id: '/_authed/approvals/$approvalId'
      path: '/approvals/$approvalId'
      fullPath: '/approvals/$approvalId'
      preLoaderRoute: typeof AuthedApprovalsApprovalIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/$appId': {
      id: '/_authed/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AuthedAppsAppIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/apps/$appId_/kill-switch/$runId': {
      id: '/_authed/apps/$appId_/kill-switch/$runId'
      path: '/apps/$appId/kill-switch/$runId'
      fullPath: '/apps/$appId/kill-switch/$runId'
      preLoaderRoute: typeof AuthedAppsAppIdKillSwitchRunIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedConnectionsRoute: typeof AuthedConnectionsRoute
  AuthedEgressRoute: typeof AuthedEgressRoute
  AuthedEnvironmentRoute: typeof AuthedEnvironmentRoute
  AuthedPeopleRoute: typeof AuthedPeopleRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedApprovalsApprovalIdRoute: typeof AuthedApprovalsApprovalIdRoute
  AuthedAppsAppIdRoute: typeof AuthedAppsAppIdRoute
  AuthedApprovalsIndexRoute: typeof AuthedApprovalsIndexRoute
  AuthedAppsAppIdKillSwitchRunIdRoute: typeof AuthedAppsAppIdKillSwitchRunIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedConnectionsRoute: AuthedConnectionsRoute,
  AuthedEgressRoute: AuthedEgressRoute,
  AuthedEnvironmentRoute: AuthedEnvironmentRoute,
  AuthedPeopleRoute: AuthedPeopleRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedApprovalsApprovalIdRoute: AuthedApprovalsApprovalIdRoute,
  AuthedAppsAppIdRoute: AuthedAppsAppIdRoute,
  AuthedApprovalsIndexRoute: AuthedApprovalsIndexRoute,
  AuthedAppsAppIdKillSwitchRunIdRoute: AuthedAppsAppIdKillSwitchRunIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
